### ISSUE TITLE
Segnalazione errori presenti nelle stringhe

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/voice-web#27]
Segnalare gli errori presenti nelle stringhe di Common Voice qui.
Inserire la frase presente su Common Voice con la correzione da applicare.
Esempio:
> Stringa errata presente su Common Voice

> Stringa corretta

(Le correzioni verranno effettuate dai revisori non appena possibile)

**Comment by dag7dev** [comment]
Per conoscere il mondo esterno sono delle folgorazioni e illuminazioniattraverso la sua esperienza di vita.

Per conoscere il mondo esterno sono delle folgorazioni e illuminazioni attraverso la sua esperienza di vita.

**Comment by dag7dev** [comment]
> laalchilazione permette di ottenere diverse derivati del petrolio con un processo definito.


> L'alchilazione permette di ottenere diverse derivati del petrolio con un processo definito.

**Comment by dag7dev** [comment]
> È cosa buona che tutta la Chiesa conosca gli sforzi intrapresi per il salvataggio di uni popolo in pericolo.


> È cosa buona che tutta la Chiesa conosca gli sforzi intrapresi per il salvataggio di un popolo in pericolo.

**Comment by dag7dev** [comment]
> 11 agosto 2016 rio de janeiro, brasile.


> 11 agosto 2016 Rio de Janeiro, Brasile.

**Comment by dag7dev** [comment]
> L’evento permetterà a tutti partecipanti di conoscere e collaborare ad oltre quaranta progetti opensource da tutto il mondo


> L’evento permetterà a tutti i  partecipanti di conoscere e collaborare ad oltre quaranta progetti opensource da tutto il mondo

**Comment by dag7dev** [comment]
> Infatti qui sono stati utilizzate diverse funzioni.


> Infatti qui sono stati utilizzate diverse funzioni.

**Comment by dag7dev** [comment]
> Dove l’obiettivo non sono il profitto ma il progetto stesso


> Dove l’obiettivo non è il profitto ma il progetto stesso

**Comment by dag7dev** [comment]
> Nel '59 vennero scoperti altri fossili in Africa e ciò confermò che era il continente della culla degli essere umani.


> Nel '59 vennero scoperti altri fossili in Africa e ciò confermò che era il continente della culla degli esseri umani.

**Comment by dag7dev** [comment]
> Se valige si potevano chiamare quelle due specie di cassette rettangolari, nere e rigide, di cuoio duro.


> Se valigie si potevano chiamare quelle due specie di cassette rettangolari, nere e rigide, di cuoio duro.

**Comment by dag7dev** [comment]
> Naturalisti e pescatori costieri conoscono bene il plamkton


> Naturalisti e pescatori costieri conoscono bene il plankton

**Comment by dag7dev** [comment]
> Mi prese da pare e disse: "Mamma, posso dirgli una cosa?"


> Mi prese da parte e disse: "Mamma, posso dirgli una cosa?"

**Comment by dag7dev** [comment]
> Migliorerebbe le mie prestazione.


> Migliorerebbe le mie prestazioni.

**Comment by dag7dev** [comment]
> Questa sezione viene messa contatto con un colorante alla volta per 15 secondi


> Questa sezione viene messa a  contatto con un colorante alla volta per 15 secondi

**Comment by dag7dev** [comment]
> Dopo la partenza che avviene con una velocità iniziale di 30 metri il secondo


> Dopo la partenza che avviene con una velocità iniziale di 30 metri al secondo

**Comment by dag7dev** [comment]
> A differenza del dorso nel quale è regolamenta l’uscita in posizione supina.


> A differenza del dorso nel quale è regolamentata l’uscita in posizione supina.

**Comment by dag7dev** [comment]
> Sieno rinnovate le operazioni di scandaglio ordinò il capitano del Condor.


> Siano rinnovate le operazioni di scandaglio ordinò il capitano del Condor.

**Comment by dag7dev** [comment]
> La società è la tecnologia sono riflessi l'una dell'altra”.


> La società e la tecnologia sono riflessi l'una dell'altra”.

**Comment by dag7dev** [comment]
> Molto sono le modifiche apportate nel regolamento


> Molte sono le modifiche apportate nel regolamento

**Comment by dag7dev** [comment]
> Forse, neppure una delle parole che aveva dette rispondeva a verità.


> Forse, neppure una delle parole che aveva detto rispondeva a verità.

**Comment by dag7dev** [comment]
> Levar la pelle a qualcuno a qualcuno.


> Levar la pelle a qualcuno.

**Comment by dag7dev** [comment]
> Le federazione sono importanti poichè gestiscono i regolamenti e le certificazioni del nuoto


> Le federazioni sono importanti poichè gestiscono i regolamenti e le certificazioni del nuoto

**Comment by dag7dev** [comment]
> Essi dovranno offrire il proprio supporto per l’organizzazione e la realizzazione delle stesse.


> Essi dovranno offrire il proprio supporto per l’organizzazione e la realizzazione della stessa.

**Comment by dag7dev** [comment]
> Spesso collegandosi al main-frame che gestisce gli scambi dei binari della metropolitani causano forti rallentamenti.


> Spesso collegandosi al main-frame che gestisce gli scambi dei binari della metropolitana causando forti rallentamenti.

**Comment by dag7dev** [comment]
> Tutto questo grazie ai diversi tratta di pace.


> Tutto questo grazie ai diversi trattati di pace.

**Comment by dag7dev** [comment]
> Nelle montagne del Giappone presso le sorgenti vulcaniche dove le acque della pozza sono scaldate del magma


> Nelle montagne del Giappone presso le sorgenti vulcaniche dove le acque della pozza sono scaldate dal magma

**Comment by dag7dev** [comment]
Non sono 125 caratteri:

> Ora Dalmor conosceva i luoghi in cui si trovavano: si trovavano nelle anguste e inospitali fosse di Terranova, così chiamate in onore dell’isola da cui proveniva re Ghurtar I, l’isola di Terranova per l’appunto.


> Ora Dalmor conosceva i luoghi in cui si trovavano
> si trovavano nelle anguste e inospitali fosse di Terranova
> così chiamate in onore dell’isola da cui proveniva re Ghurtar I, l’isola di Terranova per l’appunto.

**Comment by Sav22999** [comment]
NON SEGNALARE PIU' FRASI IN QUESTO ISSUE (Usare l'issue #33)
