### ISSUE TITLE
Segnalazione errori presenti nelle stringhe (n.2)

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/voice-web#33]
Segnalare gli errori presenti nelle stringhe di Common Voice qui.
Inserire la frase presente su Common Voice con la correzione da applicare.
Esempio:
> Stringa errata presente su Common Voice

> Stringa corretta

(Le correzioni verranno effettuate dai revisori non appena possibile)

**Comment by dag7dev** [comment]
> Contemporaneamente s'apriva lo sportello di destra e un signore su trentacinque balzò fuori.


> Contemporaneamente s'apriva lo sportello di destra e un signore sui trentacinque balzò fuori.

**Comment by dag7dev** [comment]
> Infatti il primo deve "istruire" quindi deve insegnare il saper stare in acqua, incluse le nuotare.


> Infatti il primo deve "istruire" quindi deve insegnare il saper stare in acqua, incluse le nuotate.

**Comment by dag7dev** [comment]
> Aspettare la manna del cielo.


> Aspettare la manna dal cielo.

**Comment by dag7dev** [comment]
> Chiudere la stalla quando i buoi sono scapati.


> Chiudere la stalla quando i buoi sono scappati.

**Comment by Sav22999** [comment]
> "Mettetelo a sedere e lasciatelo.
> Mettetelo a sedere e lasciatelo.

**Comment by Sav22999** [comment]
> Ed è freddo, quindi ve accontentate'.

> Ed è freddo, quindi ve accontentate.

**Comment by Sav22999** [comment]
> Dopo la partenza che avviene con una velocità iniziale di 30 metri il secondo.

> Dopo la partenza che avviene con una velocità iniziale di 30 metri al secondo.

**Comment by dag7dev** [comment]
> il maschio ha una piccola coda invece la femmina non c'è l'ha


> il maschio ha una piccola coda invece la femmina non ce l'ha

**Comment by dag7dev** [comment]
> Mio padre, Paolo Meis, scapato e insofferente di giogo.


> Mio padre, Paolo Meis, scappato e insofferente di giogo.

**Comment by dag7dev** [comment]
> Masticava con rabbia un pezzo di "toscano," facendoselo passeggiare per la bocca.


 > Masticava con rabbia un pezzo di "toscano", facendoselo passeggiare per la bocca.

**Comment by dag7dev** [comment]
> Contare i boccone a qualcuno.


> Contare i bocconi a qualcuno.

**Comment by Sav22999** [comment]
> Colui che distrugge le sicurezza di un sistema.

> Colui che distrugge la sicurezza di un sistema.

**Comment by dag7dev** [comment]
> Colui che distrugge le sicurezza di un sistema.


> Colui che distrugge la sicurezza di un sistema.

**Comment by dag7dev** [comment]
> La famiglia, che abbiamo visitata immediatamente, ne dovette aspettare la salma durante sei giorni!

> La famiglia, che abbiamo visitato immediatamente, ne dovette aspettare la salma durante sei giorni!

**Comment by dag7dev** [comment]
> Ora ci concetreremo sulla riga superiore


> Ora ci concentreremo sulla riga superiore

**Comment by dag7dev** [comment]
> Daremmo mai i nostri dati personali personali come indirizzo o data di nascita al McDonald's quando ordiniamo qualcosa?


> Daremmo mai i nostri dati personali come indirizzo o data di nascita al McDonald's quando ordiniamo qualcosa?

**Comment by dag7dev** [comment]
> Dato cheche non è necessario ottenere le licenze d'utilizzo, permette uno snellimento dei processi di adozione del software.

> Dato che non è necessario ottenere le licenze d'utilizzo, permette uno snellimento dei processi di adozione del software.

**Comment by dag7dev** [comment]
> Ho cancellato tutto dalla nostra cartella condivisa, ero preoccupato qualcun'altro potesse accederci.

> Ho cancellato tutto dalla nostra cartella condivisa, ero preoccupato che qualcun'altro potesse accederci.

**Comment by dag7dev** [comment]
> Questo uccello vive soprattutto sul terreno e si trovano vicino all'acqua ed alle paludi.

> Questo uccello vive soprattutto sul terreno e si trova vicino all'acqua ed alle paludi.

**Comment by dag7dev** [comment]
> Conosceva a memoria e menadito gli eventi registrati dalle scritture in seguito.

> Conosceva a memoria a menadito gli eventi registrati dalle scritture in seguito.

**Comment by dag7dev** [comment]
> che può corrispondere al periodo giurasico o mesozoico della terra

> che può corrispondere al periodo giurassico o mesozoico della terra

**Comment by dag7dev** [comment]
> Tutti promettono di far tornare la lirica me nessuno promette di farla restare.


> Tutti promettono di far tornare la lirica ma nessuno promette di farla restare.

**Comment by Mte90** [comment]
`Una rana nera sulla rena errò una sera, una rara rana bianca sulla rena errò un po' stanca.` da rimuovere o ci vengono a cercare

**Comment by Sav22999** [comment]
- Contemporaneamente s'apriva lo sportello di destra e un signore su trentacinque balzò fuori. ✔️ **Corretta**
- Infatti il primo deve "istruire" quindi deve insegnare il saper stare in acqua, incluse le nuotare. ❗️ **Non trovata**
- Aspettare la manna del cielo. ✔️ **Corretta**
- Chiudere la stalla quando i buoi sono scapati. ✔️ **Corretta**
- Ho preso tanto sole in questi giorni e non vedo l'ora che si faccia nuovolo di nuovo! ❗️ **Non trovata**
- "Mettetelo a sedere e lasciatelo. ❗️ **Non trovata**
- Ed è freddo, quindi ve accontentate'. ❗️ **Non trovata**
- Dopo la partenza che avviene con una velocità iniziale di 30 metri il secondo. ✔️ **Corretta**
- il maschio ha una piccola coda invece la femmina non c'è l'ha ❗️ **Non trovata**
- O, più comunemente, un braccia lungo e l'altro lo raggiunge successivamente, formando quindi l'assetto. ❗️ **Non trovata**
- Mio padre, Paolo Meis, scapato e insofferente di giogo. ✔️ **Corretta**
- Masticava con rabbia un pezzo di "toscano," facendoselo passeggiare per la bocca. ❗️ **Non trovata**
- Contare i boccone a qualcuno. ❗️ **Non trovata**
- Colui che distrugge le sicurezza di un sistema. ❗️ **Non trovata**
- Dopodichè le gambe vengono portare rannicchiate, insieme alle ginocchia che toccano la pancia. ❗️ **Non trovata**
- La famiglia, che abbiamo visitata immediatamente, ne dovette aspettare la salma durante sei giorni! ✔️ **Corretta**
- Ora ci concetreremo sulla riga superiore ❗️ **Non trovata**
- Daremmo mai i nostri dati personali personali come indirizzo o data di nascita al McDonald's quando ordiniamo qualcosa? ❗️ **Non trovata**
- Dato cheche non è necessario ottenere le licenze d'utilizzo, permette uno snellimento dei processi di adozione del software. ❗️ **Non trovata**
- Ho cancellato tutto dalla nostra cartella condivisa, ero preoccupato qualcun'altro potesse accederci. ❗️ **Non trovata**
- Questo uccello vive soprattutto sul terreno e si trovano vicino all'acqua ed alle paludi. ✔️ **Corretta**
- Conosceva a memoria e menadito gli eventi registrati dalle scritture in seguito. ✔️ **Corretta**
- che può corrispondere al periodo giurasico o mesozoico della terra ❗️ **Non trovata**
- Tutti promettono di far tornare la lirica me nessuno promette di farla restare. ✔️ **Corretta**
- Una rana nera sulla rena errò una sera, una rara rana bianca sulla rena errò un po' stanca. ✔️ **Rimossa**

### CHIUDO L'ISSUE E NE APRO UNO NUOVO
