### ISSUE TITLE
Segnalazioni errori presenti nelle stringhe (n.3)

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/voice-web#35]
Segnalare gli errori presenti nelle stringhe di Common Voice qui.
Inserire la frase presente su Common Voice con la correzione da applicare.
Esempio:
> Stringa errata presente su Common Voice

> Stringa corretta

**_Mettere un doppio spazio tra una frase e l'altra altrimenti GitHub le inserisce in un'unica "quote"_**

(Le correzioni verranno effettuate dai revisori non appena possibile)

Nel momento in cui saranno corretti gli errori, verrà pubblicato un commento con un feedback su ciascuna frase:
✔️ **Corretta**: se la frase è stata trovata ed è stata corretta
✔️ **Rimossa**: se la frase è stata trovata e rimossa, come da segnalazione
❗️ **Non trovata**: se la frase **non** è stata trovata, quindi non è stato possibile effettuare alcuna operazione
❎ **Non eseguita** (con eventuale spiegazione): se la segnalazione non è stata accettata. Per esempio, potrebbe essere una segnalazione che non presenta un errore, secondo i moderatori.

**Comment by Sav22999** [comment]
> Una delle caratteristiche che lì differenza dagli altri volatili è che hanno gli occhi di fronte.
> Una delle caratteristiche che li differenza dagli altri volatili è che hanno gli occhi di fronte.

**Comment by Sav22999** [comment]
> Inoltre, solo aziende di gradi dimensioni hanno la possibilità di sostenere le spese per l'ottenimento di un brevetto.
> Inoltre, solo aziende di grandi dimensioni hanno la possibilità di sostenere le spese per l'ottenimento di un brevetto.

**Comment by Sav22999** [comment]
Dividere la frase in 2 sub-frasi:
> Le tesle non emettono CO2 e hanno prezzi abbordabili. Il traffico a Los Angeles fa impazzire tutti?

in 

> Le tesle non emettono CO2 e hanno prezzi abbordabili.

> Il traffico a Los Angeles fa impazzire tutti?

**Comment by Sav22999** [comment]
Separare in 2 sub-frasi:

> Hai preso l'olio extravergine di oliva? È finito, ci serve!

in 

> Hai preso l'olio extravergine di oliva?

> È finito, ci serve!

**Comment by Sav22999** [comment]
> Vi raccontiamo una classica storia di vita di tutti giorni.

> Vi raccontiamo una classica storia di vita di tutti i giorni.

**Comment by Sav22999** [comment]
> Questo grande affidamento alla scienza non darà mai risposte alla domanda a cui nessun filosofo a trovato una risposta.

> Questo grande affidamento alla scienza non darà mai risposte alla domanda a cui nessun filosofo ha trovato una risposta.

**Comment by Mte90** [comment]
Dobbiamo rimuovere tutti i `°` e i numeri romani sostituirli con del testo altrimenti sono frasi da buttare.
