### ISSUE TITLE
Segnalazione errori - Periodo da 07-07-2018 a 09-07-2018

### ISSUE THREAD

**Issue by Sav22999** [MozillaItalia/voice-web#6]
# PERIODO || DA 07 LUGLIO 2018 || A 09 LUGLIO 2018

Leggere la seguente descrizione:
Questo issue è stato creato appositamente per raccogliere tutte le segnalazioni riguardo errori su Common Voice per quanto riguarda la lingua italiana (frasi troppo lunghe, errori grammaticali, frasi incomplete, ...).
Verrà riproposto con cadenza almeno mensile, tuttavia per periodi eccezionali può essere anche di durata differente. Il periodo, comunque, è riportato sia nel titolo sia ad inizio issue.
Questo per evitare che vengano effettuate numerose pullrequest. Infatti, al termine del periodo specificato, verrà effettuata da un moderatore una pullrequest contenente tutte le modifiche alle segnalazioni fatte, in questo modo si ha una SINGOLA PR piuttosto che molte.

### Si prega di seguire i seguenti accorgimenti prima di fare una segnalazione:
- Controllare, prima di inserire un commento (quindi una segnalazione) che non sia già presente in quelle già segnalate
- Essere più dettagliati possibile, spiegando qual è il problema e, magari, allegando anche una o più immagini (screenshot)
- Una segnalazione per ogni commento

**Comment by Sav22999** [comment]
FRASE LUNGA (grazie a @mone27)
![immagine](https://user-images.githubusercontent.com/32335378/42412565-fcd8fc08-820e-11e8-95e0-b6f7ffd318ec.png)

**Comment by Sav22999** [comment]
FRASE LUNGA
![immagine](https://user-images.githubusercontent.com/32335378/42412570-1a297f80-820f-11e8-8e62-5f7cc8a8b6ec.png)

**Comment by Sav22999** [comment]
ERRORE LESSICALE
![immagine](https://user-images.githubusercontent.com/32335378/42412575-2a495926-820f-11e8-8f26-6c6dcf72afcb.png)

**Comment by Sav22999** [comment]
FRASE SUPER-LUNGA (grazie @mone7)
![immagine](https://user-images.githubusercontent.com/32335378/42412584-55d45d84-820f-11e8-8c76-c8eaaca98261.png)

**Comment by Sav22999** [comment]
FRASE LUNGA (grazie @mone27)
![immagine](https://user-images.githubusercontent.com/32335378/42412588-6a5be556-820f-11e8-8623-05f0819b36d0.png)

**Comment by Mte90** [comment]
Si può chiudere?

**Comment by Sav22999** [comment]
Si, a quanto pare nessuno ha da segnalare qualcosa... mah.
